// All 16 built-in locations
const CITIES = [
  {
    id: 16,
    name: "Shellmere",
    size: "Small Village",
    traits: ["Coastal", "Lakeside", "No Mountains", "Tortle Village"],
    population: 290,
    exports: ["Woven Sea Grass", "Smoked Shellfish", "Painted Shell Crafts", "Medicinal Kelp"],
    imports: ["Iron Tools", "Timber", "Grain", "Rope"],
    flavor: "Shellmere is a low, quiet village where the lake meets the sea across a wide sandbar, and the buildings are round, thick-walled, and partially buried in the sand — built in the Tortle tradition to last centuries rather than decades. The pace of life here is deliberate, unhurried, and completely indifferent to the urgency of outsiders.",
    lore: [
      "Tortles here measure time in generations rather than years. When they say something happened 'recently,' they may mean within the last forty years. Outsiders find this deeply disorienting.",
      "The village has no formal leadership — decisions are made by consensus, which takes as long as it takes. Players needing a quick answer will wait. Players who sit with the elders and share a meal tend to do better.",
      "The sandbar between the lake and sea shifts seasonally, occasionally revealing ancient shell middens and the remains of a much older Tortle settlement buried beneath. The villagers treat these discoveries with reverent calm and rebury them carefully.",
      "A single elder named Ossivane is known across several islands as a healer and keeper of oral histories. Scholars and the desperate alike make the journey to Shellmere to speak with her.",
    ],
    shops: [
      { name: "Taverns", count: 1 },
      { name: "General Stores", count: 1 },
      { name: "Herbalist / Apothecary", count: 1 },
      { name: "Shell Craft & Artisan", count: 1 },
    ],
    factions: [
      { name: "Druidic Enclaves", count: 1, type: "nature" },
      { name: "Religious Sects", count: 1, type: "neutral" },
    ],
  },
  {
    id: 15,
    name: "Thornslip",
    size: "Small Village",
    traits: ["Coastal", "Rivers", "Mountains Very Close", "Mixed Cultures"],
    population: 460,
    exports: ["Mountain Berries & Preserves", "Smoked River Fish", "Pine Tar", "Rough Timber"],
    imports: ["Grain", "Salt", "Iron Tools", "Cloth"],
    flavor: "Thornslip is wedged into a narrow coastal shelf where a swift mountain river cuts through dense rainforest before dropping into the sea. The village is half-hidden by the tree canopy — you can sail right past it if you don't know where to look. Most people don't.",
    lore: [
      "Thornslip's obscurity is not entirely accidental. The village has quietly sheltered wanted individuals for years — not out of ideology, but because strangers who need to disappear tend to pay well and ask few questions.",
      "The river here runs unusually fast due to the mountain gradient, and periodic flash floods have destroyed and rebuilt parts of the village more than once. Everyone owns a rope and knows how to use it.",
      "Two cultural communities share the village with minimal friction — they arrived under different circumstances but both had reason to stay out of sight, which turned out to be common enough ground.",
    ],
    shops: [
      { name: "Taverns", count: 1 },
      { name: "General Stores", count: 1 },
      { name: "Herbalist / Apothecary", count: 1 },
      { name: "Boat Repair", count: 1 },
    ],
    factions: [
      { name: "Criminal Organizations", count: 1, type: "danger" },
      { name: "Religious Sects", count: 1, type: "neutral" },
    ],
  },
  {
    id: 14,
    name: "Valdrek's Perch",
    size: "Small Village",
    traits: ["Inland", "Mountain Lakes & Rivers", "Highest Peaks", "Goliath Tribe"],
    population: 340,
    exports: ["Rare Alpine Herbs", "Mountain Cat Pelts", "Hand-Forged Stone Weapons", "Smoked High-Altitude Game"],
    imports: ["Iron & Steel", "Salt", "Lowland Grain", "Rope & Cordage"],
    flavor: "Valdrek's Perch exists at an altitude where the air is thin, the wind is constant, and the view stretches to every coast on a clear day. The village is carved into a granite ridge above the snowline, its structures low and heavy against the mountain as if bracing for the next storm. Goliath elders say their ancestors built here because no enemy would follow them this high. They were right.",
    lore: [
      "The village is governed by the Stone Circle — a council of seven elders chosen by feat of endurance rather than age or lineage. Leadership here is earned, not inherited.",
      "Valdrek's Perch trades sparingly with the lowland settlements, and only through a handful of trusted intermediaries. Direct outsider contact is permitted but watched closely at all times.",
      "The high mountain lakes near the village are considered sacred ground — bathing, fishing, or drawing water without permission from the Stone Circle is a serious transgression.",
      "A druidic hermit lives alone above the village near the highest peak, visited occasionally by the elders for counsel. The hermit has not come down in over a decade.",
    ],
    shops: [
      { name: "Taverns", count: 1 },
      { name: "General Stores", count: 1 },
      { name: "Herbalist / Apothecary", count: 1 },
      { name: "Tanning & Leather Work", count: 1 },
    ],
    factions: [
      { name: "Stone Circle Council", count: 1, type: "neutral" },
      { name: "Druidic Enclaves", count: 1, type: "nature" },
    ],
  },
  {
    id: 13,
    name: "Brackfen",
    size: "Small Village",
    traits: ["Coastal", "Coastal Lake", "No Mountains", "Mixed Cultures"],
    population: 520,
    exports: ["Smoked Eel", "Reed Mats & Baskets", "Waterfowl Feathers", "Crab"],
    imports: ["Grain", "Iron Tools", "Rope", "Salted Pork"],
    flavor: "Brackfen sits where a wide shallow lake nearly meets the sea, separated only by a thin strip of reedy land. The village straddles both — half its buildings face the lake, half face the coast, and the strip between them is perpetually soggy. It has the feeling of a place that could be swallowed by water at any moment and has simply decided not to worry about it.",
    lore: [
      "The village is split between two communities — lake-folk and sea-folk — who arrived separately and never quite merged. They share a single tavern and precious little else, though open hostility is rare.",
      "A traveling merchant stops here twice a year with goods from distant cities. The entire village treats the arrival like a holiday. Players arriving around this time will find Brackfen unusually lively.",
      "Something has been taking the crab traps at night — not stealing them, just emptying them and leaving them in strange arrangements on the shore. The village is more unnerved than they're letting on.",
    ],
    shops: [
      { name: "Taverns", count: 1 },
      { name: "General Stores", count: 1 },
      { name: "Fish Markets", count: 1 },
      { name: "Net & Reed Weaver", count: 1 },
    ],
    factions: [
      { name: "Religious Sects", count: 1, type: "neutral" },
    ],
  },
  {
    id: 12,
    name: "Skarnpool",
    size: "Small Village",
    traits: ["Coastal", "Mountain Lake", "Mountains Very Close", "Single Culture"],
    population: 680,
    exports: ["Salted Mountain Trout", "Goat Milk & Cheese", "Felted Wool"],
    imports: ["Iron Tools", "Grain", "Candles & Oil"],
    flavor: "Skarnpool is barely a village — a cluster of stone and turf houses huddled around a cold mountain lake that drains in a short, violent waterfall straight to the sea below. The people here are few, hardy, and deeply unwelcoming of anyone who doesn't already know their name.",
    lore: [
      "The village has no formal government — disputes are settled by the eldest resident, currently a weathered woman named Harva who has held the role for twenty years and shows no signs of stepping aside.",
      "The lake is believed by every villager to be bottomless. No one swims in it. When asked why, they change the subject.",
      "A small druidic presence tends the mountain slopes above the village, watching over the alpine goat herds and the rare cold-weather herbs that grow near the snowline.",
    ],
    shops: [
      { name: "Taverns", count: 1 },
      { name: "General Stores", count: 1 },
      { name: "Herbalist / Apothecary", count: 1 },
    ],
    factions: [
      { name: "Druidic Enclaves", count: 1, type: "nature" },
    ],
  },
  {
    id: 11,
    name: "Spindrift Notch",
    size: "Moderate Town/Village",
    traits: ["Coastal", "Rivers", "Mountains Very Close", "Mixed Cultures"],
    population: 4100,
    exports: ["Smoked Fish", "Mountain Pine Resin", "Hand-Carved Rope Pulleys", "Cliff Honey"],
    imports: ["Grain", "Iron Tools", "Cloth", "Preserved Fruits"],
    flavor: "Spindrift Notch is built into a narrow gap in the coastal cliffside where a fast mountain river has cut its way to the sea over millennia. The town clings to both walls of the notch on terraced ledges, connected by rope bridges and a complicated system of pulleys and lifts that the locals operate with casual ease and that terrifies every visitor.",
    lore: [
      "The pulley and lift system that connects the notch terraces is maintained by a tight-knit guild of riggers who have passed the knowledge down for generations. Outsiders are not taught. Ever.",
      "The notch creates a natural wind tunnel that makes the town louder, windier, and colder than anywhere nearby — locals are famously tough and famously blunt.",
      "A spy network has taken root here, drawn by the notch's position as a natural observation point over a wide stretch of coastline. Someone in this town is watching ships and reporting to someone in one of the larger cities.",
      "The river running through the notch floor is fast and cold year-round — it powers several small mills and is considered unswimmable by anyone with sense.",
    ],
    shops: [
      { name: "Taverns", count: 3 },
      { name: "General Stores", count: 2 },
      { name: "Blacksmithing", count: 1 },
      { name: "Butcher / Food Market", count: 2 },
      { name: "Fish Markets", count: 2 },
      { name: "Herbalist / Apothecary", count: 2 },
      { name: "Rigger & Rope Supplies", count: 2 },
      { name: "Mill & Grain Merchant", count: 1 },
    ],
    factions: [
      { name: "Government Agencies", count: 1, type: "neutral" },
      { name: "Religious Sects", count: 1, type: "neutral" },
      { name: "Spy Network", count: 1, type: "danger" },
      { name: "Riggers' Guild", count: 1, type: "neutral" },
    ],
  },
  {
    id: 10,
    name: "Craghaven",
    size: "Moderate Town/Village",
    traits: ["Coastal", "Rivers", "Mountains Very Close", "Mixed Cultures"],
    population: 3500,
    exports: ["Quarried Stone", "Mountain Goat Cheese", "Smoked Mountain Game", "Carved Stonework"],
    imports: ["Seafood", "Grain", "Cloth", "Rope & Rigging"],
    flavor: "Craghaven is pinched between a sheer cliff face and a rocky coastline, its buildings hewn directly from the mountain stone wherever possible. The river that cuts through town arrives as a waterfall and leaves as a fast-running channel straight into the sea — the sound of rushing water never stops.",
    lore: [
      "The town exists primarily because of its quarry, which produces a distinctive grey-green stone prized for construction in wealthier cities. The quarry bosses hold more practical power than the town's nominal government.",
      "A small mercenary outfit called the Crag Watch was originally hired to protect the quarry. They've since become the town's de facto law enforcement, a role they've grown comfortable with.",
      "Two cultural communities live here in proximity but not harmony — the mountain folk who work the quarry and the coastal settlers who work the water. They share the same taverns but little else.",
      "A druidic enclave keeps a quiet presence at the base of the cliffs, tending the native mountain flora that clings to the rockface. They have an uneasy relationship with the quarry operations.",
    ],
    shops: [
      { name: "Taverns", count: 3 },
      { name: "General Stores", count: 2 },
      { name: "Blacksmithing", count: 2 },
      { name: "Butcher / Food Market", count: 2 },
      { name: "Fish Markets", count: 2 },
      { name: "Stonemason & Carver", count: 2 },
      { name: "Herbalist / Apothecary", count: 1 },
      { name: "Mining & Quarry Supplies", count: 2 },
    ],
    factions: [
      { name: "Mercenary Organizations", count: 1, type: "warning" },
      { name: "Government Agencies", count: 1, type: "neutral" },
      { name: "Religious Sects", count: 1, type: "neutral" },
      { name: "Druidic Enclaves", count: 1, type: "nature" },
      { name: "Quarry Bosses", count: 1, type: "neutral" },
    ],
  },
  {
    id: 9,
    name: "Sandy Hollows",
    size: "Moderate Town/Village",
    traits: ["Coastal", "Lakes & Rivers", "No Mountains", "Single Culture"],
    population: 3200,
    exports: ["Woven Baskets & Nets", "Salted Fish", "Dyed Linen", "Canoes & Small Vessels"],
    imports: ["Iron & Steel", "Stone", "Spices", "Foreign Luxuries"],
    flavor: "Thaloven is a tight, proud fishing community stretched along a flat coastal lagoon where a river fans out into shallow lake-like pools before reaching the sea. Every family has been here for generations, every face is familiar, and outsiders are tolerated rather than welcomed — at least until they've proven themselves useful.",
    lore: [
      "The town is governed by the Elder Tide, a council of the oldest fishing family matriarchs and patriarchs. Their word is law, and their memories are long.",
      "Thaloven has no criminal organizations to speak of — not because crime doesn't happen, but because the community handles its own problems quietly and without outside interference.",
      "A single religious sect dominates spiritual life entirely: the Lagoon Keepers, who believe the shallow lagoon pools are windows into the afterlife. Funerary rites involve releasing the dead into the lagoon waters.",
      "The town's boat-builders are considered the finest craftspeople for small shallow-draft vessels in the region — a well-regarded Thaloven canoe fetches a premium price in any city.",
    ],
    shops: [
      { name: "Taverns", count: 2 },
      { name: "General Stores", count: 2 },
      { name: "Fish Markets", count: 3 },
      { name: "Butcher / Food Market", count: 1 },
      { name: "Boat Builder & Repair", count: 2 },
      { name: "Net & Rope Maker", count: 2 },
      { name: "Dyer & Linen Weaver", count: 1 },
      { name: "Herbalist / Apothecary", count: 1 },
    ],
    factions: [
      { name: "Government Agencies", count: 1, type: "neutral" },
      { name: "Religious Sects", count: 1, type: "neutral" },
      { name: "Elder Tide Council", count: 1, type: "neutral" },
    ],
  },
  {
    id: 8,
    name: "Mossgate",
    size: "Moderate Town/Village",
    traits: ["Inland", "Swamp Rivers", "Distant Mountains", "Mixed Cultures"],
    population: 2900,
    exports: ["Peat & Bog Fuel", "Swamp Herbs & Fungi", "Preserved Meats", "Alligator Hide", "Rare Mosses"],
    imports: ["Dry Timber", "Grain & Flour", "Iron Tools", "Salt", "Clean Cloth"],
    flavor: "Mossgate sits at the edge of a dark and sprawling swamp, where the rivers slow to a crawl and the water turns the color of black tea. The town itself is built on raised platforms and ancient stilts, connected by rope bridges and boardwalks that creak and sway in the humid air. Nothing here is fully dry.",
    lore: [
      "The swamp is locally known as the Drowned Margin — few outsiders who wander into it unguided come back out. The town's guides charge handsomely for escort, and they're worth every coin.",
      "A druidic enclave called the Bogwardens has tended the swamp for generations. They are not welcoming to those who come to exploit it, and they have ways of discouraging visitors they dislike.",
      "Rumors persist of something old living in the deepest part of the swamp — townspeople don't discuss it with outsiders, but they leave offerings at the water's edge on the new moon.",
      "A small cult has taken root in the town, drawn by the swamp's eerie atmosphere. They believe the dark water is a conduit to something beneath the world.",
    ],
    shops: [
      { name: "Taverns", count: 2 },
      { name: "General Stores", count: 2 },
      { name: "Blacksmithing", count: 1 },
      { name: "Butcher / Food Market", count: 1 },
      { name: "Herbalist / Apothecary", count: 3 },
      { name: "Tanning & Leather Work", count: 2 },
      { name: "Swamp Guide Services", count: 2 },
      { name: "Alchemist", count: 1 },
    ],
    factions: [
      { name: "Cults", count: 1, type: "danger" },
      { name: "Government Agencies", count: 1, type: "neutral" },
      { name: "Religious Sects", count: 1, type: "neutral" },
      { name: "Druidic Enclaves", count: 1, type: "nature" },
    ],
  },
  {
    id: 7,
    name: "Wellowmere",
    size: "Moderate Town/Village",
    traits: ["Coastal", "River Access", "Distant Mountains", "Mixed Cultures"],
    population: 3800,
    exports: ["Dried Fish", "River Reeds & Thatch", "Crab & Shellfish", "Salted Pork"],
    imports: ["Iron Tools", "Cloth & Thread", "Grain", "Candles & Oil"],
    flavor: "Wellowmere is the kind of town that doesn't appear on most maps but should — a weathered coastal settlement where the river meets a wide tidal estuary, and where the smell of salt and woodsmoke is constant. Everyone knows everyone, and strangers are noticed immediately.",
    lore: [
      "The town sits at a natural waypoint between two larger cities, making it a quiet but reliable stop for river traders who don't want to pay the fees at bigger ports.",
      "A small but stubborn smuggling ring operates out of the estuary — they've been doing it for three generations and consider it a family trade.",
      "The local religious sect venerates the river mouth itself, believing the tidal pull is the breath of a sleeping god. They're mostly harmless but deeply suspicious of outsiders who disrespect the estuary.",
    ],
    shops: [
      { name: "Taverns", count: 3 },
      { name: "General Stores", count: 2 },
      { name: "Blacksmithing", count: 1 },
      { name: "Butcher / Food Market", count: 2 },
      { name: "Fish Markets", count: 2 },
      { name: "Shipping / Trade Vendors", count: 2 },
      { name: "Herbalist / Apothecary", count: 1 },
      { name: "Boat Repair", count: 1 },
    ],
    factions: [
      { name: "Criminal Organizations", count: 1, type: "danger" },
      { name: "Government Agencies", count: 1, type: "neutral" },
      { name: "Religious Sects", count: 1, type: "neutral" },
    ],
  },
  {
    id: 6,
    name: "Ashcrag",
    size: "Large City",
    traits: ["Coastal", "Rivers", "Mountains Very Close", "Mixed Cultures"],
    population: 20300,
    exports: ["Refined Metal Goods", "Mountain Timber", "River Jade", "Medicinal Mountain Herbs", "Fortified Wine"],
    imports: ["Seafood", "Grain & Rice", "Dyed Textiles", "Exotic Animals", "Foreign Spellcraft"],
    flavor: "Thyravoss is the oldest of the island cities — you can tell by the way the mountain has been carved into it as much as it was built against it. Ancient stone aqueducts carry river water down from the peaks through districts that have changed hands a dozen times over centuries, each new culture leaving its mark on the architecture.",
    lore: [
      "The city's age means its laws are a labyrinthine patchwork of old decrees, cultural compacts, and grudging compromises — lawyers and fixers are among the most powerful people in Thyravoss.",
      "River jade, found only in the mountain streams above the city, is the source of much of Thyravoss's wealth and most of its conflicts. The Jade Registry controls licensing, but smuggling is rampant.",
      "Three criminal organizations operate here, each rooted in a different cultural community — they rarely cooperate but maintain an unspoken rule against open warfare in the market districts.",
      "A powerful religious institution called the Mountain Covenant claims the peaks above the city as sacred ground, charging tolls on mountain expeditions and controlling access to the highest river jade deposits.",
    ],
    shops: [
      { name: "Book Stores", count: 4 },
      { name: "Magic Shops", count: 4 },
      { name: "Taverns", count: 13 },
      { name: "General Stores", count: 8 },
      { name: "Clothing Stores", count: 5 },
      { name: "Blacksmithing", count: 6 },
      { name: "Butcher / Food Market", count: 6 },
      { name: "Fish Markets", count: 3 },
      { name: "Shipping / Trade Vendors", count: 7 },
      { name: "Tanning & Leather Work", count: 3 },
      { name: "Cartographer", count: 2 },
      { name: "Alchemist", count: 4 },
      { name: "Jade & Gemstone Dealer", count: 5 },
      { name: "Herbalist / Apothecary", count: 5 },
      { name: "Winery & Spirits", count: 3 },
      { name: "Money Changer / Bank", count: 3 },
      { name: "Mining Supplies", count: 3 },
      { name: "Legal Scrivener & Notary", count: 3 },
    ],
    factions: [
      { name: "Criminal Organizations", count: 3, type: "danger" },
      { name: "Mercenary Organizations", count: 3, type: "warning" },
      { name: "Cults", count: 2, type: "danger" },
      { name: "Government Agencies", count: 4, type: "neutral" },
      { name: "Religious Sects", count: 4, type: "neutral" },
      { name: "Spy Network", count: 2, type: "danger" },
      { name: "Druidic Enclaves", count: 1, type: "nature" },
      { name: "Arcane Society", count: 1, type: "arcane" },
      { name: "Jade Registry", count: 1, type: "neutral" },
      { name: "Mountain Covenant", count: 1, type: "neutral" },
      { name: "Merchants' League", count: 1, type: "neutral" },
      { name: "Aqueduct Authority", count: 1, type: "neutral" },
    ],
  },
  {
    id: 5,
    name: "Kethavar",
    size: "Large City",
    traits: ["Coastal", "Lakes & Rivers", "Mountains Very Close", "Mixed Cultures"],
    population: 17800,
    exports: ["Mountain Ore", "Carved Stone", "Alpine Herbs", "Waterfall-Milled Flour", "Gemstones"],
    imports: ["Seafood", "Tropical Timber", "Dyed Cloth", "Grain", "Foreign Luxury Goods"],
    flavor: "Kethavar is wedged between cliff faces and crashing surf, its buildings stacked up the mountain slopes like an argument that refuses to end. Waterfalls cut through the city itself, powering mills and filling cisterns, and the roar of falling water is the city's constant backdrop.",
    lore: [
      "The mountain passes above the city are the only overland routes to the island's interior — whoever controls Kethavar controls the flow of ore and stone to the coast, a fact every faction in the city is acutely aware of.",
      "A druidic enclave called the Stonebreath Circle tends the mountain springs and the watersheds that feed the city's waterfalls. They are deeply respected — and occasionally feared.",
      "The city's mixed population includes a significant number of mountain-dwelling folk who came down for trade and never left, creating cultural friction with the coastal communities in the lower districts.",
      "An arcane society called the Resonance works from a tower carved directly into the cliff face, studying the unusual magical properties that the nearby mountain peaks seem to generate.",
    ],
    shops: [
      { name: "Magic Shops", count: 4 },
      { name: "Taverns", count: 11 },
      { name: "General Stores", count: 7 },
      { name: "Clothing Stores", count: 4 },
      { name: "Blacksmithing", count: 6 },
      { name: "Butcher / Food Market", count: 5 },
      { name: "Fish Markets", count: 4 },
      { name: "Shipping / Trade Vendors", count: 7 },
      { name: "Tanning & Leather Work", count: 4 },
      { name: "Cartographer", count: 2 },
      { name: "Alchemist", count: 3 },
      { name: "Gemstone & Mineral Dealer", count: 4 },
      { name: "Stonemason & Sculptor", count: 3 },
      { name: "Herbalist / Apothecary", count: 4 },
      { name: "Mill & Grain Merchant", count: 3 },
      { name: "Mining Supplies", count: 3 },
    ],
    factions: [
      { name: "Criminal Organizations", count: 2, type: "danger" },
      { name: "Mercenary Organizations", count: 3, type: "warning" },
      { name: "Cults", count: 1, type: "danger" },
      { name: "Government Agencies", count: 3, type: "neutral" },
      { name: "Religious Sects", count: 3, type: "neutral" },
      { name: "Spy Network", count: 2, type: "danger" },
      { name: "Druidic Enclaves", count: 1, type: "nature" },
      { name: "Arcane Society", count: 1, type: "arcane" },
      { name: "Miners' Guild", count: 1, type: "neutral" },
      { name: "Pass Wardens", count: 1, type: "neutral" },
      { name: "Coastal Traders' League", count: 1, type: "neutral" },
    ],
  },
  {
    id: 4,
    name: "Dravenoch",
    size: "Large City",
    traits: ["Coastal", "Lakes & Rivers", "Distant Mountains", "Mixed Cultures"],
    population: 19600,
    exports: ["Salted Fish", "Lacewood Furniture", "Woven Reed Goods", "Lake Salts", "Smoked Fowl"],
    imports: ["Iron & Steel Tools", "Mountain Ore", "Grain", "Wine & Spirits", "Arcane Reagents"],
    flavor: "Dravenoch clings to the edge of a coastal bluff where a wide lake drains into the sea through a braided network of channels. The city is split across multiple elevations — the bluff districts look down, literally and figuratively, on the channel settlements below.",
    lore: [
      "The upper bluff districts are dominated by older, established families who control most of the city's legal institutions. The channel districts below are rougher, more transient, and far more interesting.",
      "A vast underground salt trade flows through the channel district — lake salts are highly prized but the extraction rights are disputed between three different factions.",
      "Two mercenary companies maintain a fragile truce in the city, both hired at various times by the bluff families to suppress channel district unrest.",
      "A druidic enclave known as the Reed Speakers tends the lake's edge and the wetland birds — they serve as neutral mediators between the bluff and channel districts, though their patience is wearing thin.",
    ],
    shops: [
      { name: "Taverns", count: 12 },
      { name: "General Stores", count: 8 },
      { name: "Clothing Stores", count: 5 },
      { name: "Blacksmithing", count: 4 },
      { name: "Butcher / Food Market", count: 7 },
      { name: "Fish Markets", count: 6 },
      { name: "Shipping / Trade Vendors", count: 9 },
      { name: "Tanning & Leather Work", count: 3 },
      { name: "Cartographer", count: 2 },
      { name: "Alchemist", count: 2 },
      { name: "Smokehouse & Curer", count: 5 },
      { name: "Furniture & Woodcraft", count: 4 },
      { name: "Salt Merchant", count: 3 },
      { name: "Boat Repair & Rigging", count: 3 },
      { name: "Herbalist / Apothecary", count: 3 },
      { name: "Money Changer / Bank", count: 2 },
    ],
    factions: [
      { name: "Criminal Organizations", count: 2, type: "danger" },
      { name: "Mercenary Organizations", count: 2, type: "warning" },
      { name: "Cults", count: 1, type: "danger" },
      { name: "Government Agencies", count: 3, type: "neutral" },
      { name: "Religious Sects", count: 3, type: "neutral" },
      { name: "Spy Network", count: 1, type: "danger" },
      { name: "Druidic Enclaves", count: 1, type: "nature" },
      { name: "Bluff Families Council", count: 1, type: "neutral" },
      { name: "Channel District Guild", count: 1, type: "neutral" },
      { name: "Salt Extractors' Union", count: 1, type: "neutral" },
    ],
  },
  {
    id: 3,
    name: "Harrowgate",
    size: "Large City",
    traits: ["Coastal", "River Access", "No Mountains", "Mixed Cultures"],
    population: 22800,
    exports: ["Woven Silk & Dye", "Exotic Spices", "River Clay Pottery", "Tropical Fruit", "Rope & Sailcloth"],
    imports: ["Timber", "Stone", "Iron & Steel", "Livestock", "Cold-Climate Furs"],
    flavor: "Flat and sprawling, Solvethara has no mountains to hide behind and no natural defenses — so it built its walls from wealth instead. The city is a maze of open-air markets, canal streets, and merchant towers that lean slightly toward the sea as if perpetually doing business.",
    lore: [
      "With no geographic chokepoints, Solvethara has historically survived through diplomacy and coin rather than warfare — making it a city of smooth-talking power brokers.",
      "The river delta splits the city into two unofficial halves: the Old Mouth (established families and guilds) and the New Mouth (immigrants, newcomers, and ambitious outsiders). Tension between them is constant.",
      "A powerful Merchants' Consortium effectively runs city government, with elected officials serving as little more than its public face.",
      "Three distinct religious sects each claim the river itself as sacred — their competing river-blessing ceremonies have caused at least two diplomatic incidents.",
    ],
    shops: [
      { name: "Magic Shops", count: 3 },
      { name: "Taverns", count: 14 },
      { name: "General Stores", count: 9 },
      { name: "Clothing Stores", count: 8 },
      { name: "Blacksmithing", count: 3 },
      { name: "Butcher / Food Market", count: 8 },
      { name: "Fish Markets", count: 5 },
      { name: "Shipping / Trade Vendors", count: 11 },
      { name: "Cartographer", count: 3 },
      { name: "Alchemist", count: 2 },
      { name: "Dye & Textile Merchant", count: 5 },
      { name: "Spice Merchant", count: 4 },
      { name: "Pottery & Ceramics", count: 3 },
      { name: "Rope & Sailmaker", count: 3 },
      { name: "Money Changer / Bank", count: 4 },
      { name: "Boat Repair & Rigging", count: 3 },
    ],
    factions: [
      { name: "Criminal Organizations", count: 3, type: "danger" },
      { name: "Mercenary Organizations", count: 2, type: "warning" },
      { name: "Cults", count: 1, type: "danger" },
      { name: "Government Agencies", count: 3, type: "neutral" },
      { name: "Religious Sects", count: 3, type: "neutral" },
      { name: "Spy Network", count: 2, type: "danger" },
      { name: "Merchants' Consortium", count: 1, type: "neutral" },
      { name: "Dyers' & Weavers' Guild", count: 1, type: "neutral" },
      { name: "Sailors' Union", count: 1, type: "neutral" },
      { name: "River Wardens", count: 1, type: "neutral" },
    ],
  },
  {
    id: 2,
    name: "Dunhollow",
    size: "Large City",
    traits: ["Coastal", "Lakes & Rivers", "Distant Mountains", "Mixed Cultures"],
    population: 21200,
    exports: ["Freshwater Pearls", "Smoked Eel", "Lacquered Wood", "Medicinal Herbs", "Salt"],
    imports: ["Mountain Stone", "Iron Ingots", "Silk", "Spices", "Arcane Instruments"],
    flavor: "Built across three river mouths and a brackish lake, Mirethkal is a city of bridges, stilted homes, and perpetual mist. Every district smells of something different — smoked fish, lacquer fumes, or night-blooming herbs.",
    lore: [
      "The Lake Council governs the city — seven seats, each representing a different cultural district. Deadlock is common.",
      "Two rival criminal brotherhoods operate smuggling routes: one through the lake, one through the coastal inlets. Open conflict is rare but brutal when it erupts.",
      "A druidic enclave called the Stillwater Circle maintains the lake's health; they have more political power than they let on.",
      "Foreign merchants arriving by sea must register with the Harbor Ledger, a government agency infamous for selective enforcement.",
    ],
    shops: [
      { name: "Book Stores", count: 3 },
      { name: "Magic Shops", count: 2 },
      { name: "Taverns", count: 12 },
      { name: "General Stores", count: 7 },
      { name: "Clothing Stores", count: 5 },
      { name: "Blacksmithing", count: 2 },
      { name: "Butcher / Food Market", count: 6 },
      { name: "Fish Markets", count: 7 },
      { name: "Shipping / Trade Vendors", count: 8 },
      { name: "Cartographer", count: 2 },
      { name: "Alchemist", count: 3 },
      { name: "Freshwater Pearl Dealer", count: 2 },
      { name: "Boat Builder & Repair", count: 4 },
      { name: "Herbalist / Apothecary", count: 6 },
      { name: "Money Changer / Bank", count: 2 },
      { name: "Smokehouse & Curer", count: 4 },
    ],
    factions: [
      { name: "Criminal Organizations", count: 2, type: "danger" },
      { name: "Mercenary Organizations", count: 2, type: "warning" },
      { name: "Cults", count: 1, type: "danger" },
      { name: "Government Agencies", count: 4, type: "neutral" },
      { name: "Religious Sects", count: 4, type: "neutral" },
      { name: "Spy Network", count: 1, type: "danger" },
      { name: "Druidic Enclaves", count: 1, type: "nature" },
      { name: "Merchants' Guild", count: 1, type: "neutral" },
      { name: "Fishers' Collective", count: 1, type: "neutral" },
      { name: "Lake Council", count: 1, type: "neutral" },
    ],
  },
  {
    id: 1,
    name: "Tideworn",
    size: "Large City",
    traits: ["Coastal", "River Delta", "Distant Mountains", "Mixed Cultures"],
    population: 18400,
    exports: ["Fish", "Tropical Timber", "River Pearls", "Dyed Cloth"],
    imports: ["Ore & Metals", "Livestock", "Preserved Grain", "Arcane Reagents"],
    flavor: "Where the river meets the sea — a sprawling, loud, fragrant city of a dozen languages and twice as many ambitions. The delta docks run day and night.",
    lore: [
      "Three criminal orgs control docks, river trade, and interior markets — coexisting uneasily.",
      "Four religious sects reflect mixed-culture tensions over temple district territory.",
      "The Druidic Enclave operates quietly, tied to the river's health and mountain watershed.",
      "The Harbor Authority and Merchants' Guild act in their own interest despite government ties.",
    ],
    shops: [
      { name: "Book Stores", count: 3 },
      { name: "Magic Shops", count: 3 },
      { name: "Taverns", count: 11 },
      { name: "General Stores", count: 7 },
      { name: "Clothing Stores", count: 5 },
      { name: "Blacksmithing", count: 4 },
      { name: "Butcher / Food Market", count: 6 },
      { name: "Fish Markets", count: 5 },
      { name: "Shipping / Trade Vendors", count: 8 },
      { name: "Tanning & Leather Work", count: 2 },
      { name: "Cartographer", count: 2 },
      { name: "Alchemist", count: 2 },
      { name: "Jeweler & Pearl Trader", count: 3 },
      { name: "Boat Repair & Rigging", count: 3 },
      { name: "Herbalist / Apothecary", count: 2 },
      { name: "Money Changer / Bank", count: 2 },
    ],
    factions: [
      { name: "Criminal Organizations", count: 3, type: "danger" },
      { name: "Mercenary Organizations", count: 2, type: "warning" },
      { name: "Cults", count: 1, type: "danger" },
      { name: "Government Agencies", count: 3, type: "neutral" },
      { name: "Religious Sects", count: 4, type: "neutral" },
      { name: "Spy Network", count: 2, type: "danger" },
      { name: "Druidic Enclaves", count: 1, type: "nature" },
      { name: "Merchants' Guild", count: 1, type: "neutral" },
      { name: "Sailors' Union", count: 1, type: "neutral" },
      { name: "Harbor Authority", count: 1, type: "neutral" },
    ],
  },
];

const SIZE_COLORS = {
  "Large City": "#c8a96e",
  "Moderate Town/Village": "#7eb89a",
  "Small Village": "#9ab0c8",
  "Landmark / Ruin": "#b07a9e",
  "Dungeon": "#7a6090",
  "Custom City": "#c8a96e",
};

const FACTION_COLORS = {
  danger: { bg: "#3a1a1a", text: "#e07070", border: "#6b2f2f" },
  warning: { bg: "#2e2410", text: "#d4a550", border: "#6b5020" },
  neutral: { bg: "#1a1e2e", text: "#8090c0", border: "#2e3a5e" },
  nature: { bg: "#162213", text: "#5db87a", border: "#2a4a30" },
  arcane: { bg: "#1e1530", text: "#a07ed8", border: "#3d2870" },
};

const FACTION_LEGEND = {
  danger: "Hostile/Hidden", warning: "Mercenary",
  neutral: "Civic/Faith", nature: "Natural", arcane: "Arcane"
};
